# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5bb46a36061fc23f60057b00ff5ddc8f9d6e4534e00180cb6cf1b0c2389dad5fdb51f227d0876a997cfd8854076bb032aa722e01cf792a201a3cc329cfb05bd2

test:
  secret_key_base: 4705ab0b4703752e1836e4cee031fa14d5e356c124efc0ec336494c351433c1d994a716071a2e8dbc95df22bc265cd9a4f691b141ef224f3aa878359eae91428

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
